### ISSUE TITLE
Pre-Condition failed while executing test after importing the archetype

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat-archetype-aem-bdd#5]
<java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:136)
	at org.openqa.selenium.firefox.GeckoDriverService.access$000(GeckoDriverService.java:41)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.usingFirefoxBinary(GeckoDriverService.java:108)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:204)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:137)>

**Comment by DeChrish** [comment]
When i changed from <bobcat.version>1.1.4</bobcat.version> to <bobcat.version>1.2.1</bobcat.version>, am getting the above error.

**Comment by mkrzyzanowski** [comment]
Hi @DeChrish!

This sounds like the same issue as in https://github.com/Cognifide/bobcat/issues/198 - you can find a workaround in that ticket before we fix it on our end.
